
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SNCRegistration.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class Attendance
{

    public string Description { get; set; }

    public Nullable<bool> Volunteer { get; set; }

    public Nullable<bool> Participant { get; set; }

    public int AttendanceID { get; set; }

}

}
