//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNCRegistration.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadContact()
        {
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public int LeadContactID { get; set; }
        public string BSType { get; set; }
        public string UnitChapterNumber { get; set; }
        public string LeadContactFirstName { get; set; }
        public string LeadContactLastName { get; set; }
        public string LeadContactAddress { get; set; }
        public string LeadContactCity { get; set; }
        public string LeadContactState { get; set; }
        public string LeadContactZip { get; set; }
        public string LeadContactCellPhone { get; set; }
        public string LeadContactEmail { get; set; }
        public string VolunteerAttendingCode { get; set; }
        public Nullable<bool> SaturdayDinner { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public string Booth { get; set; }
        public string Comments { get; set; }
        public bool LeadContactShirtOrder { get; set; }
        public string LeadContactShirtSize { get; set; }
        public string LeaderGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
