//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNCRegistration.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int VolunteerID { get; set; }
        public string VolunteerFirstName { get; set; }
        public string VolunteerLastName { get; set; }
        public string VolunteerAge { get; set; }
        public Nullable<int> LeadContactID { get; set; }
        //public bool VolunteerShirtOrder { get; set; }
        bool _VolunteerShirtOrder = true;
        public bool VolunteerShirtOrder
        {
            get
            {
                return _VolunteerShirtOrder;
            }
            set
            {
                _VolunteerShirtOrder = value;
            }
        }
        public string VolunteerShirtSize { get; set; }
        public string VolunteerAttendingCode { get; set; }
        public Nullable<bool> SaturdayDinner { get; set; }
        public string UnitChapterNumber { get; set; }
        public string Comments { get; set; }
    
        public virtual LeadContact LeadContact { get; set; }
    }
}
